### ISSUE TITLE
Replace `express-template` with `express-api-template`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/express-template#24] opened 2016-10-18 02:27 UTC
Some spots were missed, e.g. in `server.js`

**Comment by raq929** [comment] 2016-11-29 16:03
Is this a duplicate of #21, or is that issue trying to say something different?

**Comment by gaand** [comment] 2016-11-29 17:41
https://github.com/ga-wdi-boston/express-api-template/blob/master/server.js#L26

**Closed as completed** 2016-12-03 23:30 UTC
